databases:
  - name: proyect
    plan: free
    databaseName: proyect
    user: proyect

services:
  - type: web
    plan: free
    name: proyect
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m uvicorn proyect.asgi:application --reload' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyect
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4